# Generated by Django 3.2.25 on 2025-08-31 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='boat_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('id_proof', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=500)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='officer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trolling_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishind_area', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.CharField(max_length=500)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.officer_table')),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('From', models.CharField(max_length=20)),
                ('To', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat')),
            ],
        ),
        migrations.CreateModel(
            name='suggections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggection', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat_owner')),
            ],
        ),
        migrations.CreateModel(
            name='safety_tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.officer_table')),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.officer_table')),
            ],
        ),
        migrations.CreateModel(
            name='illegal_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=100)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat')),
            ],
        ),
        migrations.CreateModel(
            name='emergency_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat')),
            ],
        ),
        migrations.CreateModel(
            name='drowing_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.FileField(upload_to='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat_owner')),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat_owner'),
        ),
        migrations.CreateModel(
            name='ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.boat')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.monitoring')),
            ],
        ),
    ]
