# Generated by Django 3.2.25 on 2025-11-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assignedboat_officer_add_tip_passwordresetotp_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rules',
        ),
    ]
