# Generated by Django 5.2.10 on 2026-02-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_report_illegal_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency_report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
            preserve_default=False,
        ),
    ]
