# Generated by Django 5.2.10 on 2026-02-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_emergency_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.illegal_activity'),
        ),
    ]
